"""Constants describing AeroQSP and qSpider behaviour."""

AERO_THEME_URL = "https://raw.githubusercontent.com/QSPFoundation/qspider/main/public/themes/aero.html"
THEME_NAME = "aero-compat"

# Default skin values from the AeroQSP help (old.qsp.org/misc/aero/help.htm) and DefaultSkin.as.
AERO_DEFAULT_FONT_SIZE = 18

AERO_EFFECTS = {
    "fade",
    "quake",
    "blur",
    "h_blinds",
    "v_blinds",
    "l_slide",
    "r_slide",
    "u_slide",
    "d_slide",
    "iris",
    "photo",
    "pixels",
    "rotate",
    "v_squeeze",
    "h_squeeze",
    "zoom",
    "wipe1",
    "wipe2",
    "wipe3",
    "wipe4",
}
# Effects that qSpider does not implement (libs/renderer/src/transformers/aero/aero-effects.ts).
QSPIDER_MISSING_EFFECTS = {"h_blinds", "v_blinds", "pixels"}

# AeroQSP's own colour table for <font color="name"> (helpers/HTML.as). Several entries differ from CSS.
AERO_NAMED_COLORS = {
    "black": "#000000",
    "silver": "#C0C0C0",
    "grey": "#808080",
    "white": "#FFFFFF",
    "maroon": "#800000",
    "red": "#FF0000",
    "purple": "#800080",
    "fuchsia": "#FF00FF",
    "green": "#008000",
    "lime": "#00FF00",
    "olive": "#808000",
    "yellow": "#FFFF00",
    "navy": "#000080",
    "blue": "#0000FF",
    "teal": "#008080",
    "aqua": "#00FFFF",
    "aquamarine": "#70DB93",
    "blue violet": "#9F5F9F",
    "brown": "#A52A2A",
    "cadet blue": "#5F9F9F",
    "coral": "#FF7F00",
    "cornflower blue": "#42426F",
    "cyan": "#00FFFF",
    "dark grey": "#2F2F2F",
    "dark green": "#2F4F2F",
    "dark olive green": "#4F4F2F",
    "dark orchid": "#9932CC",
    "dark slate blue": "#6B238E",
    "dark slate grey": "#2F4F4F",
    "dark turquoise": "#7093DB",
    "dim grey": "#545454",
    "firebrick": "#8E2323",
    "forest green": "#238E23",
    "gold": "#CC7F32",
    "goldenrod": "#DBDB70",
    "green yellow": "#93DB70",
    "indian red": "#4F2F2F",
    "khaki": "#9F9F5F",
    "light blue": "#BFD8D8",
    "light grey": "#C0C0C0",
    "light steel blue": "#8F8FBC",
    "lime green": "#32CC32",
    "light magenta": "#FF00FF",
    "magenta": "#FF00FF",
    "medium aquamarine": "#32CC99",
    "medium grey": "#646464",
    "medium blue": "#3232CC",
    "medium forest green": "#6B8E23",
    "medium goldenrod": "#EAEAAD",
    "medium orchid": "#9370DB",
    "medium sea green": "#426F42",
    "medium slate blue": "#7F00FF",
    "medium spring green": "#7FFF00",
    "medium turquoise": "#70DBDB",
    "medium violet red": "#DB7093",
    "midnight blue": "#2F2F4F",
    "orange": "#CC3232",
    "orange red": "#FF007F",
    "orchid": "#DB70DB",
    "pale green": "#8FBC8F",
    "pink": "#FFC0CB",
    "plum": "#EAADEA",
    "salmon": "#6F4242",
    "sea green": "#238E6B",
    "sienna": "#8E6B23",
    "sky blue": "#3299CC",
    "slate blue": "#007FFF",
    "spring green": "#00FF7F",
    "steel blue": "#236B8E",
    "tan": "#DB9370",
    "thistle": "#D8BFD8",
    "turquoise": "#ADEAEA",
    "violet": "#4F2F4F",
    "violet red": "#CC3299",
    "wheat": "#D8D8BF",
    "yellow green": "#99CC32",
}

MEDIA_EXTENSIONS = (
    "png",
    "jpg",
    "jpeg",
    "gif",
    "bmp",
    "webp",
    "svg",
    "ico",
    "mp3",
    "wav",
    "ogg",
    "mid",
    "midi",
    "webm",
    "mp4",
    "swf",
    "ttf",
    "otf",
    "woff",
    "woff2",
    "qsp",
    "gam",
    "qsps",
    "css",
    "js",
    "txt",
)
GAME_EXTENSIONS = (".qsp", ".gam")
GAME_SOURCE_EXTENSIONS = (*GAME_EXTENSIONS, ".qsps")
JUNK_NAMES = {"thumbs.db", "desktop.ini", ".ds_store"}
JUNK_EXTENSIONS = {".qproj", ".bak", ".swf"}

CSS_LENGTH_PROPS = (
    "font-size",
    "letter-spacing",
    "text-indent",
    "border-width",
    "width",
    "height",
    "left",
    "top",
    "margin",
    "margin-left",
    "margin-right",
    "margin-top",
    "margin-bottom",
    "padding",
    "padding-left",
    "padding-right",
    "padding-top",
    "padding-bottom",
)
GLOBAL_CSS_SELECTORS = {"body", "a", "p", "div", "span", "table", "td", "tr", "img", "html", "*", "li", "ul", "ol"}

IDENT_CHARS = r"[0-9A-Za-z_А-Яа-яЁё]"
