"""The aero-compat theme: qSpider's aero theme with AeroQSP defaults and Flash-like layout rules."""

import re
import urllib.request
from importlib import resources
from pathlib import Path

from . import __version__
from .constants import THEME_NAME

QSPIDER_THEME_URL = "https://raw.githubusercontent.com/QSPFoundation/qspider/main/public/themes/aero.html"
BUNDLED_THEME = "qspider-aero.html"

COMPAT_CSS = """/* Generated by aero2qspider: AeroQSP compatibility overrides for the qSpider aero theme. */

/* AeroQSP tiles background images from the top-left corner instead of scaling them to fit. */
.main-block,
.aero-player-foreground,
qsp-stats,
qsp-main,
qsp-objects,
.regular-actions,
.integrated-actions {
  background-repeat: repeat;
  background-size: auto;
  background-position: 0 0;
}

/* In Flash an empty panel does not catch clicks, so links under it keep working.
   Let clicks pass through panels and catch them only on the actual content. */
qsp-stats,
qsp-main,
qsp-objects,
qsp-actions,
qsp-stats .qsp-scroll-area,
qsp-main .qsp-scroll-area,
qsp-objects .qsp-scroll-area,
qsp-actions .qsp-scroll-area {
  pointer-events: none;
}
qsp-stats-content,
qsp-main-content,
qsp-actions-list > *,
qsp-objects-list > *,
.qsp-scrollbar {
  pointer-events: auto;
}

/* In Flash a table that contains <center> is stretched to the full width (the default
   action/object/menu formats are tables, so centred item names relied on it). */
table:has(center) {
  width: 100%;
}
"""


def build_theme(source: str, font_size: int) -> str:
    theme = source.replace('name="qspider:aero"', f'name="{THEME_NAME}"', 1)
    if THEME_NAME not in theme:
        raise ValueError('the template has no <qspider-theme name="qspider:aero"> tag')
    theme = theme.replace(
        '<css-link src="qspider:themes/aero.css"></css-link>',
        '<css-link src="qspider:themes/aero.css"></css-link>\n  <css-link src="aero-compat.css"></css-link>',
        1,
    )
    theme = re.sub(r'(from="FSIZE"[^>]*default-value=")\d+(")', rf"\g<1>{font_size}\2", theme, count=1)
    header = (
        f"<!-- Generated by aero2qspider {__version__} from the qSpider aero theme (MIT, (c) Sergii Kostyrko): "
        f"FSIZE default {font_size}, tiled backgrounds, click-through panels. -->\n"
    )
    return header + theme


def load_aero_theme(source: str | None) -> tuple[str, str]:
    """Return the template and where it came from: a path, a URL, "latest" or the bundled copy."""
    if source == "latest":
        source = QSPIDER_THEME_URL
    if source and source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source, timeout=30) as response:
            return response.read().decode("utf-8"), source
    if source:
        return Path(source).read_text(encoding="utf-8"), source
    bundled = resources.files("aero2qspider") / "data" / BUNDLED_THEME
    return bundled.read_text(encoding="utf-8"), "bundled qSpider 1.4 theme"
